---
Name: eventbriteroutes
After:
  - '#rootroutes'
  - '#coreroutes'
---
SilverStripe\Control\Director:
  rules:
    'eventbrite': 'DorsetDigital\SilverStripeEventBrite\Control\WebhookController'
    'viewevent': 'DorsetDigital\SilverStripeEventBrite\Control\EventController'